-- 
-- 导出表中的数据 `jieqi_system_blocks`
-- 

INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '电子书列表区块', 'obook', 'block_obooklist', 'BlockObookObooklist', 0, '最近更新', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_obooklist.html”，在/modules/obook/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分割“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按最近更新），允许以下几种设置：1、“lastupdate” - 按最近更新；2、“postdate” - 按最新入库；3、“toptime” - 按本站推荐；4、“goodnum” - 按收藏数量；5、“allsale” - 按总销售量；6、“monthsale” - 按月销售量；7、“weeksale” - 按周销售量；8、“daysale” - 按日销售量；9、“size” - 按电子书字数；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是电子书类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分割，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是出版商（默认留空表示全部出版商），此处使用得是出版商序号而不是名称，多个序号可以用“|”分隔<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,,0,0” 表示显示15条最近更新的作品，其中第二个参数留空，所以使用默认的15条。', '', 'lastupdate,15,0,0,0,0', 'block_obooklist.html', 0, 1, 50100, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '电子书推荐', 'obook', 'block_obookcommend', 'BlockObookObookcommend', 0, '电子书推荐', '&nbsp;&nbsp;&nbsp;&nbsp;本区块根据参数里面的ID，显示推荐的电子书。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置推荐的电子书序号作为参数，不同参数之间用英文“|”分隔。比如： “123|234|456|678” ', '', '', 'block_obookcommend.html', 0, 4, 50200, 0, 0, 0, 0, 2);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '分类阅读', 'obook', 'block_sort', 'BlockObookSort', 0, '分类阅读', '', '', '', '', 0, 0, 51100, 0, 0, 0, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '电子书搜索', 'obook', 'block_search', 'BlockObookSearch', 1, '电子书搜索', '', '', '', '', 0, 0, 51200, 0, 0, 0, 0, 0);

-- 
-- 导出表中的数据 `jieqi_system_configs`
-- 

INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'staticurl', '阅读页面根地址', '', '用于电子书购买和阅读在不同服务器场合，留空表示用系统默认路径', 0, 1, '', 10100, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'dynamicurl', '交易页面根地址', '', '用于电子书购买和阅读在不同服务器场合，留空表示用系统默认路径', 0, 1, '', 10200, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'imagetype', '封面图片文件后缀', '.jpg', '', 0, 1, '', 10300, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'imagedir', '封面图片文件保存目录', 'image', '', 0, 1, '', 10400, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'imageurl', '访问封面图片的URL', '', '图片用相对路径的话此处留空，否则用完整url，最后不带斜杠', 0, 1, '', 10500, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'hideobookwords', '文章需要过滤的词语', '', '多个单词用空格分开', 0, 1, '', 10510, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'sameobookname', '文章标题是否允许重复', '0', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 10550, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'authtypeset', '是否允许自动排版', '1', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 10560, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'autotypeset', '默认自动排版', '1', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 10570, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'pagenum', '电子书每页显示数', '20', '', 0, 3, '', 10600, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'topcachenum', '电子书列表缓存几个页面', '10', '', 0, 3, '', 10700, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'bookcasenum', '电子书默认最大收藏数', '30', '', 0, 3, '', 10800, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'minsearchlen', '搜索关键字最少长度', '4', '', 0, 3, '', 10900, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'minsearchtime', '两次搜索间隔时间', '30', '', 0, 3, '', 11000, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'indexcols', '电子书目录每行显示几列', '4', '', 0, 3, '', 11100, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'fakeprefix', '伪静态页面目录前缀', '', '用户如果设置了目录前缀，伪静态页面将在根目录下使用该前缀生成目录。这样可以减少伪静态页面的目录深度，但是会增加根目录下的目录数。', 0, 1, '', 20100, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'fakefile', '伪静态文件后缀', '.htm', '使用伪静态页面时，该后缀文件需要用php来解析', 0, 1, '', 20200, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'fakeinfo', '电子书信息页面是否使用伪静态', '0', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 20300, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'fakesort', '电子书分类页面是否使用伪静态', '0', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 20400, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'fakeinitial', '首字母分类页面是否使用伪静态', '0', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 20500, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'faketoplist', '排行榜页面是否使用伪静态', '0', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 20600, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkstartx', '文字离图片左边距离', '20', '（象素点）', 0, 3, '', 30100, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkstarty', '文字离图片顶部距离', '50', '（象素点）', 0, 3, '', 30200, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obklinewidth', '阅读时一行显示几个字节', '80', '一个汉字是2个字节，英文字母1个字节', 0, 3, '', 30300, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkfontsize', '阅读字体大小', '14', '', 0, 3, '', 30400, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkfontjt', '简体字库文件路径', 'C:/WINNT/Fonts/simsun.ttc', '', 0, 1, '', 30420, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkfontft', '繁体字库文件路径', 'C:/WINNT/Fonts/simsun.ttc', '', 0, 1, '', 30440, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkcharconvert', '图片文字是否进行繁简转换', '1', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 30460, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkimagetype', '生成图片格式', 'png', '', 0, 1, '', 30500, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'jpegquality', 'jpeg图片质量', '90', '范围为 0～100 的整数，数值越大结果图片效果越好，但尺寸也越大，本参数仅生成jpeg格式图片时有效。', 0, 3, '', 30550, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkimagecolor', '图片背景颜色', '#ffffff', '', 0, 1, '', 30600, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obktextcolor', '阅读字体颜色', '#000000', '', 0, 1, '', 30700, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkangle', '字体倾斜角度', '0', '', 0, 3, '', 30800, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkshadowcolor', '字体阴影颜色', '#000000', '', 0, 1, '', 30900, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkshadowdeep', '字体阴影深度', '0', '0 表示不使用阴影', 0, 3, '', 31000, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkwatertext', '是否加文字水印及水印位置', '0', '本功能需要 GD 库支持才能使用，对 JPG/PNG/GIF 格式的图片有效', 0, 7, 'a:3:{i:0;s:8:"不加水印";i:1;s:8:"图片四角";i:2;s:8:"背景平铺";}', 31050, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkwaterformat', '文字水印格式', '', '这里设置的文字水印，在实际显示时候<{$userid}>会替换成雨用户ID，<{$username}>替换成用户名', 0, 1, '', 31060, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkwatercolor', '文字水印颜色', '#ff6600', '', 0, 1, '', 31100, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkwatersize', '文字水印字体大小', '16', '', 0, 3, '', 31200, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkwaterangle', '文字水印倾斜角度', '45', '', 0, 3, '', 31300, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obkwaterpct', '文字水印透明度', '30', '', 0, 3, '', 31400, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obookwater', '是否加图片水印及水印位置', '0', '本功能需要 GD 库支持才能使用，对 JPG/PNG/GIF 格式的图片有效', 0, 7, 'a:11:{i:0;s:8:"不加水印";i:1;s:8:"顶部居左";i:2;s:8:"顶部居中";i:3;s:8:"顶部居右";i:4;s:8:"中部居左";i:5;s:8:"中部居中";i:6;s:8:"中部居右";i:7;s:8:"底部居左";i:8;s:8:"底部居中";i:9;s:8:"底部居右";i:10;s:8:"随机位置";}', 31500, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obookwimage', '水印图片文件', 'watermark.gif', '允许 JPG/PNG/GIF 格式，默认只需填文件名，放在 modules/obook/images 目录下', 0, 1, '', 31600, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obookwtrans', '水印图片与原图片的融合度', '30', '范围为 1～100 的整数，数值越大水印图片透明度越低。', 0, 3, '', 31700, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obookreadhead', '阅读文字头部附加内容', '', '阅读一个电子书章节时候，内容头部和尾部可以附加一些预先设置的内容，比如网站名称、版权声明等。', 0, 2, '', 32100, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'obookreadfoot', '阅读文字尾部附加内容', '', '阅读一个电子书章节时候，内容头部和尾部可以附加一些预先设置的内容，比如网站名称、版权声明等。', 0, 2, '', 32200, '阅读设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'scoreobook', '发布新电子书增加积分', '5', '', 0, 3, '', 40100, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'scorechapter', '发布电子书章节增加积分', '5', '', 0, 3, '', 40200, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'wordsperegold', '默认几个汉字售价一虚拟币', '300', '', 0, 3, '', 40300, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'obook', 'priceround', '按字节计算虚拟币时非整数处理方式', '0', '', 0, 7, 'a:3:{i:0;s:8:"四舍五入";i:1;s:8:"只舍不入";i:2;s:8:"只入不舍";}', 40400, '积分设置');

-- 
-- 导出表中的数据 `jieqi_system_modules`
-- 

INSERT INTO `jieqi_system_modules` (`mid`, `name`, `caption`, `description`, `version`, `lastupdate`, `weight`, `publish`, `modtype`) VALUES (0, 'obook', '在线电子书', '在线阅读模式的电子书', 140, 0, 0, 1, 0);

-- 
-- 导出表中的数据 `jieqi_system_power`
-- 

INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'obook', 'newobook', '发布电子书', '只能以自己名义发布电子书', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'obook', 'transobook', '转载电子书', '可以以他人名义名义发布', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'obook', 'manageallobook', '管理电子书', '管理所有电子书', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'obook', 'needcheck', '发布电子书不需要审查', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'obook', 'viewbuylog', '查看购买记录', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'obook', 'customprice', '允许自定电子书价格', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'obook', 'freeread', '免费阅读电子书', '', '');
