<?php
$jieqiConfigs['system']['useradminpnum'] = '50';
$jieqiConfigs['system']['userpnum'] = '200';
$jieqiConfigs['system']['topuserpnum'] = '100';
$jieqiConfigs['system']['userlogpnum'] = '50';
$jieqiConfigs['system']['onlinetime'] = '1800';
$jieqiConfigs['system']['messagepnum'] = '30';
$jieqiConfigs['system']['messagelimit'] = '50';
$jieqiConfigs['system']['maxdaymsg'] = '0';
$jieqiConfigs['system']['friendspnum'] = '50';
$jieqiConfigs['system']['maxfriends'] = '50';
$jieqiConfigs['system']['checkcodelogin'] = '0';
$jieqiConfigs['system']['usegd'] = '0';
$jieqiConfigs['system']['regtimelimit'] = '0';
$jieqiConfigs['system']['usernamelimit'] = '0';
$jieqiConfigs['system']['avatardir'] = 'avatar';
$jieqiConfigs['system']['avatarurl'] = '';
$jieqiConfigs['system']['avatartype'] = '.gif .jpg .jpeg .png';
$jieqiConfigs['system']['avatarcut'] = '1';
$jieqiConfigs['system']['avatarsize'] = '20';
$jieqiConfigs['system']['ptopicpnum'] = '0';
$jieqiConfigs['system']['ppostpnum'] = '0';
$jieqiConfigs['system']['scoreregister'] = '10';
$jieqiConfigs['system']['scorelogin'] = '3';
$jieqiConfigs['system']['sendmsgscore'] = '0';
$jieqiConfigs['system']['adclickscore'] = '1';
$jieqiConfigs['system']['maxadclick'] = '5';
$jieqiConfigs['system']['ppostneedscore'] = '0';
$jieqiConfigs['system']['scoreptopic'] = '0';
$jieqiConfigs['system']['mailtype'] = '1';
$jieqiConfigs['system']['maildelimiter'] = '1';
$jieqiConfigs['system']['mailserver'] = '';
$jieqiConfigs['system']['mailport'] = '25';
$jieqiConfigs['system']['mailauth'] = '1';
$jieqiConfigs['system']['mailfrom'] = '';
$jieqiConfigs['system']['mailuser'] = '';
$jieqiConfigs['system']['mailpassword'] = '';
$jieqiConfigs['system']['posttitlemax'] = '60';
$jieqiConfigs['system']['postintervaltime'] = '0';
$jieqiConfigs['system']['postdenywords'] = '';
$jieqiConfigs['system']['postreplacewords'] = '替换规则每条一行，写法为：“from=to”表示内容“from”将被替换成“to”。也可以只写“from”，这样内容中的“from”会替换成“**”，相当于隐藏关键词效果。';
$jieqiConfigs['system']['postminsize'] = '0';
$jieqiConfigs['system']['postmaxsize'] = '0';
$jieqiConfigs['system']['postdenyrubbish'] = '0';
$jieqiConfigs['system']['postcheckcode'] = '0';

?>