document.write('<select name=bcolor id=bcolor onchange="javascript:saveSet(),document.getElementById(\'read_page\').style.backgroundColor=this.options[this.selectedIndex].value;">')
document.write('<option style="background-color: #E9FAFF" value="#E9FAFF">底色</option>')
document.write('<option style="background-color: #f6f6f6" value="#E6F3FF">默认</option>')
document.write('<option style="background-color: #ffffff" value="#ffffff">白色</option>')
document.write('<option style="background-color: #e3e8f7" value="#e3e8f7">淡蓝</option>')
document.write('<option style="background-color: #daebfc" value="#daebfc">蓝色</option>')
document.write('<option style="background-color: #ebeaea" value="#ebeaea">淡灰</option>')
document.write('<option style="background-color: #e7e3e6" value="#e7e3e6">灰色</option>')
document.write('<option style="background-color: #dedcd8" value="#dedcd8">深灰</option>')
document.write('<option style="background-color: #d8d7d7" value="#d8d7d7">暗灰</option>')
document.write('<option style="background-color: #E9FAFF" value="#E9FAFF">绿色</option>')
document.write('<option style="background-color: #f9fbdd" value="#f9fbdd">明黄</option>')
document.write('</select>')

document.write('<select name=txtcolor id=txtcolor onchange="javascript:saveSet(),document.getElementById(\'content\').style.color=this.options[this.selectedIndex].value;">')
document.write('<option value="#333333">字色</option>')
document.write('<option value="#000000">黑色</option>')
document.write('<option value="#ff0000">红色</option>')
document.write('<option value="#006600">绿色</option>')
document.write('<option value="#0000ff">蓝色</option>')
document.write('<option value="#660000">棕色</option>')
document.write('</select>')

document.write('<select name=fonttype id=fonttype onchange="javascript:saveSet(),document.getElementById(\'content\').style.fontSize=this.options[this.selectedIndex].value;">')
document.write('<option value="16px" >字号</option>')
document.write('<option value="12px" >小号</option>')
document.write('<option value="14px" >较小</option>')
document.write('<option value="16px" >中号</option>')
document.write('<option value="18px" >较大</option>')
document.write('<option value="24px" >大号</option>')
document.write('</select>')

document.write('<select name=scrollspeed id=scrollspeed onchange="javascript:saveSet(),setSpeed(this.value)">')
document.write('<option value="5">滚屏</option>')
document.write('<option value="1">1</option>')
document.write('<option value="2">2</option>')
document.write('<option value="3">3</option>')
document.write('<option value="4">4</option>')
document.write('<option value="5">5</option>')
document.write('<option value="6">6</option>')
document.write('<option value="7">7</option>')
document.write('<option value="8">8</option>')
document.write('<option value="9">9</option>')
document.write('<option value="10">10</option>')
document.write('</select>');


//<input name=scrollspeed id=scrollspeed onchange="javascript:saveSet(),setSpeed();" size=2 value=5> 