<?php
/**
 * read RSA Key from XML File
 *    the xml file is generated by .NET System.Security.Cryptography.RSACryptoServiceProvider 
 *
 *    By JinsongQiu, Zhejiang University
 *
 * @category   jieqicms
 * @package    pay
 */
class KeyFile {
    var $tags;
    var $values;
    
    function KeyFile($filename)
    {
    	$data = implode("", file($filename));
    	
    	$parser = xml_parser_create();
    	
    	xml_parser_set_option($parser, XML_OPTION_CASE_FOLDING, 0);
    	xml_parser_set_option($parser, XML_OPTION_SKIP_WHITE, 1);
    	
    	xml_parse_into_struct($parser, $data, $this->values, $this->tags);
    	
    	xml_parser_free($parser);
    }
    
    function getPublicKey(&$modulus, &$exponent)
    {
    	$i = $this->tags["Modulus"][0];
    	$modulus = $this->values[$i]["value"];
    	
    	$i = $this->tags["Exponent"][0];
    	$exponent = $this->values[$i]["value"];
    }
    
    function getPrivateKey(&$modulus, &$d)
    {
    	$i = $this->tags["Modulus"][0];
    	$modulus = $this->values[$i]["value"];
    	
    	$i = $this->tags["D"][0];
    	$d = $this->values[$i]["value"];
    }
    
    function getCRTPrivateKey(&$modulus, &$p, &$q, &$dp, &$dq, &$inverseQ)
    {
    	$i = $this->tags["Modulus"][0];
    	$modulus = $this->values[$i]["value"];
    	
    	$i = $this->tags["P"][0];
    	$p = $this->values[$i]["value"];

    	$i = $this->tags["Q"][0];
    	$q = $this->values[$i]["value"];

    	$i = $this->tags["DP"][0];
    	$dp = $this->values[$i]["value"];

    	$i = $this->tags["DQ"][0];
    	$dq = $this->values[$i]["value"];

    	$i = $this->tags["InverseQ"][0];
    	$inverseQ = $this->values[$i]["value"];
    }
}
 
?>