<?php 
//showtype 位運算，1111分別表示 網站所有頁、模塊所有頁、模塊首頁、網站首頁
 $jieqiBlocks['1']['bid'] = '1';
$jieqiBlocks['1']['blockname'] = '用戶登錄';
$jieqiBlocks['1']['module'] = 'system';
$jieqiBlocks['1']['filename'] = 'block_login';
$jieqiBlocks['1']['classname'] = 'BlockSystemLogin';
$jieqiBlocks['1']['side'] = '0';
$jieqiBlocks['1']['title'] = '用戶登錄';
$jieqiBlocks['1']['vars'] = '';
$jieqiBlocks['1']['template'] = '';
$jieqiBlocks['1']['contenttype'] = '0';
$jieqiBlocks['1']['custom'] = '0';
$jieqiBlocks['1']['publish'] = '1';
$jieqiBlocks['1']['hasvars'] = '0';
$jieqiBlocks['2']['bid'] = '2';
$jieqiBlocks['2']['blockname'] = '用戶狀態';
$jieqiBlocks['2']['module'] = 'system';
$jieqiBlocks['2']['filename'] = 'block_userstatus';
$jieqiBlocks['2']['classname'] = 'BlockSystemUserstatus';
$jieqiBlocks['2']['side'] = '0';
$jieqiBlocks['2']['title'] = '用戶狀態';
$jieqiBlocks['2']['vars'] = '';
$jieqiBlocks['2']['template'] = '';
$jieqiBlocks['2']['contenttype'] = '4';
$jieqiBlocks['2']['custom'] = '0';
$jieqiBlocks['2']['publish'] = '2';
$jieqiBlocks['2']['hasvars'] = '0';
?>
