<?php
$jieqiCollect['sitename'] = '思路客';
$jieqiCollect['siteurl'] = 'http://www.siluke.com/';
$jieqiCollect['subarticleid'] = 'floor($articleid/1000)';
$jieqiCollect['subchapterid'] = '';
$jieqiCollect['proxy_host'] = '';
$jieqiCollect['proxy_port'] = '';
$jieqiCollect['autoclear'] = '0';
$jieqiCollect['defaultfull'] = '0';
$jieqiCollect['referer'] = '1';
$jieqiCollect['pagecharset'] = 'auto';
$jieqiCollect['urlarticle'] = 'http://www.siluke.com/modules/article/articleinfo.php?id=<{articleid}>';
$jieqiCollect['articletitle']['left'] = '<h1>';
$jieqiCollect['articletitle']['right'] = '</h1>';
$jieqiCollect['articletitle']['middle'] = '!!!!';
$jieqiCollect['author']['left'] = '作&nbsp;&nbsp;&nbsp; 者：<a href="http://www.siluke.com/modules/article/authorarticle.php?author=~">';
$jieqiCollect['author']['right'] = '</a></td>';
$jieqiCollect['author']['middle'] = '!!!!';
$jieqiCollect['sort']['left'] = '<td width="25%">类&nbsp;&nbsp;&nbsp; 别：';
$jieqiCollect['sort']['right'] = '</td>';
$jieqiCollect['sort']['middle'] = '!!!!';
$jieqiCollect['keyword'] = '';
$jieqiCollect['intro']['left'] = '内容简介：</span><br />';
$jieqiCollect['intro']['right'] = '<span class="hottext">';
$jieqiCollect['intro']['middle'] = '****';
$jieqiCollect['articleimage']['left'] = '<img src="';
$jieqiCollect['articleimage']['right'] = '" border="0" width="100" height="125" align="right" hspace="5" vspace="5" />';
$jieqiCollect['articleimage']['middle'] = '~~~~';
$jieqiCollect['filterimage'] = 'http://www.siluke.com/modules/article/images/nocover.jpg';
$jieqiCollect['indexlink'] = '';
$jieqiCollect['fullarticle'] = '<td>文章状态：已完成</td>';
$jieqiCollect['sortid']['玄幻小说'] = '1';
$jieqiCollect['sortid']['修真小说'] = '2';
$jieqiCollect['sortid']['武侠小说'] = '2';
$jieqiCollect['sortid']['都市小说'] = '3';
$jieqiCollect['sortid']['校园小说'] = '3';
$jieqiCollect['sortid']['官场小说'] = '3';
$jieqiCollect['sortid']['穿越小说'] = '3';
$jieqiCollect['sortid']['军事小说'] = '4';
$jieqiCollect['sortid']['网游小说'] = '6';
$jieqiCollect['sortid']['竞技小说'] = '6';
$jieqiCollect['sortid']['末世小说'] = '7';
$jieqiCollect['sortid']['恐怖小说'] = '8';
$jieqiCollect['sortid']['科幻小说'] = '7';
$jieqiCollect['sortid']['同人小说'] = '1';
$jieqiCollect['sortid']['其他小说'] = '10';
$jieqiCollect['urlindex'] = 'http://www.siluke.com/0/<{subarticleid}>/<{articleid}>/';
$jieqiCollect['volume']['left'] = '<dt>';
$jieqiCollect['volume']['right'] = '</dt>';
$jieqiCollect['volume']['middle'] = '!!!!';
$jieqiCollect['chapter']['left'] = '<dd><a href="$.html" title="';
$jieqiCollect['chapter']['right'] = '">';
$jieqiCollect['chapter']['middle'] = '!!!!';
$jieqiCollect['chapterid']['left'] = '<dd><a href="';
$jieqiCollect['chapterid']['right'] = '.html" title="!">';
$jieqiCollect['chapterid']['middle'] = '$$$$';
$jieqiCollect['urlchapter'] = 'http://www.siluke.com/0/<{subarticleid}>/<{articleid}>/<{chapterid}>.html';
$jieqiCollect['content']['left'] = '<script>read_content_up();</script>';
$jieqiCollect['content']['right'] = '</div>
<script>read_link_up();</script>';
$jieqiCollect['content']['middle'] = '****';
$jieqiCollect['contentfilter'] = '思路客
www.siluke.com';
$jieqiCollect['contentreplace'] = '读吧
www.du8.org';
$jieqiCollect['collectimage'] = '1';
$jieqiCollect['imagetranslate'] = '0';
$jieqiCollect['addimagewater'] = '0';
$jieqiCollect['imagebgcolor'] = '';
$jieqiCollect['imageareaclean'] = '';
$jieqiCollect['imagecolorclean'] = '';
$jieqiCollect['listcollect']['0']['title'] = '新书';
$jieqiCollect['listcollect']['0']['urlpage'] = 'http://www.siluke.com/paihangbang/lastupdate_/<{pageid}>/';
$jieqiCollect['listcollect']['0']['articleid']['left'] = '<td class="odd"><a href="http://www.siluke.com/0/$/';
$jieqiCollect['listcollect']['0']['articleid']['right'] = '/">';
$jieqiCollect['listcollect']['0']['articleid']['middle'] = '$$$$';
$jieqiCollect['listcollect']['0']['startpageid'] = '1';
$jieqiCollect['listcollect']['0']['nextpageid'] = '++';
$jieqiCollect['listcollect']['0']['maxpagenum'] = '5';

?>