<?php
$jieqiCollect['sitename'] = '起点中文网';
$jieqiCollect['siteurl'] = 'http://www.qidian.com';
$jieqiCollect['subarticleid'] = '';
$jieqiCollect['subchapterid'] = '';
$jieqiCollect['proxy_host'] = '';
$jieqiCollect['proxy_port'] = '';
$jieqiCollect['autoclear'] = '0';
$jieqiCollect['defaultfull'] = '0';
$jieqiCollect['referer'] = '1';
$jieqiCollect['pagecharset'] = 'auto';
$jieqiCollect['urlarticle'] = 'http://www.qidian.com/Book/<{articleid}>.aspx';
$jieqiCollect['articletitle']['left'] = '<h1 class="zsfontBT"><b>';
$jieqiCollect['articletitle']['right'] = '</b>&nbsp;!<span class="zsfont12a"';
$jieqiCollect['articletitle']['middle'] = '!!!!';
$jieqiCollect['author']['left'] = 'target="_blank" class="green">';
$jieqiCollect['author']['right'] = '</a></span></h1>';
$jieqiCollect['author']['middle'] = '!!!!';
$jieqiCollect['sort']['left'] = '<td class="zsfont12a"><strong>小说大类：</strong>';
$jieqiCollect['sort']['right'] = '</td>
 <td class="zsfont12a"><strong>总推荐';
$jieqiCollect['sort']['middle'] = '!!!!';
$jieqiCollect['keyword']['left'] = '<strong>小说关键字：</strong>';
$jieqiCollect['keyword']['right'] = '<br />!</td>!</tr>';
$jieqiCollect['keyword']['middle'] = '!!!!';
$jieqiCollect['intro']['left'] = '<td height="20px">&nbsp;!</td>!</tr>!<tr>!<td class="zsfont12a" style="~">';
$jieqiCollect['intro']['right'] = '<br />!<br />!<strong>小说关键字：</strong>';
$jieqiCollect['intro']['middle'] = '****';
$jieqiCollect['articleimage']['left'] = '<a href="/Book/$.aspx"><img src="';
$jieqiCollect['articleimage']['right'] = '" width="120px" height="150px" border="0"';
$jieqiCollect['articleimage']['middle'] = '~~~~';
$jieqiCollect['filterimage'] = 'http://image.cmfu.com/books/0.jpg';
$jieqiCollect['indexlink'] = '';
$jieqiCollect['fullarticle'] = '已完成';
$jieqiCollect['sortid']['玄幻'] = '1';
$jieqiCollect['sortid']['魔法'] = '1';
$jieqiCollect['sortid']['武侠'] = '2';
$jieqiCollect['sortid']['仙侠'] = '2';
$jieqiCollect['sortid']['历史'] = '4';
$jieqiCollect['sortid']['军事'] = '4';
$jieqiCollect['sortid']['都市'] = '3';
$jieqiCollect['sortid']['言情'] = '3';
$jieqiCollect['sortid']['推理'] = '5';
$jieqiCollect['sortid']['灵异'] = '8';
$jieqiCollect['sortid']['游戏'] = '6';
$jieqiCollect['sortid']['竞技'] = '6';
$jieqiCollect['sortid']['科幻'] = '7';
$jieqiCollect['sortid']['同人'] = '6';
$jieqiCollect['sortid']['美文'] = '9';
$jieqiCollect['sortid']['default'] = '10';
$jieqiCollect['urlindex'] = 'http://www.qidian.com/BookReader/<{articleid}>.aspx';
$jieqiCollect['volume']['left'] = '<div class=\'chat\'><b>';
$jieqiCollect['volume']['right'] = '</strong>[ <a!>   分卷阅读 </a>';
$jieqiCollect['volume']['middle'] = '!!!!';
$jieqiCollect['chapter']['left'] = 'class=\'BookName\' title=\'字数：~\'>';
$jieqiCollect['chapter']['right'] = '</a></td>';
$jieqiCollect['chapter']['middle'] = '!!!!';
$jieqiCollect['chapterid']['left'] = '<td style=\'width:!><a href=\'$,';
$jieqiCollect['chapterid']['right'] = '.aspx\' class=\'BookName\' title=';
$jieqiCollect['chapterid']['middle'] = '$$$$';
$jieqiCollect['urlchapter'] = 'http://www.qidian.com/BookReader/<{articleid}>,<{chapterid}>.aspx';
$jieqiCollect['content']['left'] = '<div id="content" align="left">!<script src=\'';
$jieqiCollect['content']['right'] = '\'></script>';
$jieqiCollect['content']['middle'] = '~~~~';
$jieqiCollect['contentfilter'] = '<div!>!</div>
<span!>!</span>
<a!>!</a>
起点中文网
欢迎广大书友光临阅读，最新、最快、最火的连载作品尽在起点原创！';
$jieqiCollect['contentreplace'] = '';
$jieqiCollect['collectimage'] = '1';
$jieqiCollect['imagetranslate'] = '0';
$jieqiCollect['addimagewater'] = '0';
$jieqiCollect['imagebgcolor'] = '';
$jieqiCollect['imageareaclean'] = '';
$jieqiCollect['imagecolorclean'] = '';
$jieqiCollect['listcollect']['0']['title'] = '最近更新';
$jieqiCollect['listcollect']['0']['urlpage'] = 'http://www.qidian.com/Book/BookUpdateList.aspx?ChannelId=-1&StartTime=<{pageid}>';
$jieqiCollect['listcollect']['0']['articleid']['left'] = '= new Book(\'';
$jieqiCollect['listcollect']['0']['articleid']['right'] = '\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',~);';
$jieqiCollect['listcollect']['0']['articleid']['middle'] = '$$$$';
$jieqiCollect['listcollect']['0']['startpageid'] = '';
$jieqiCollect['listcollect']['0']['nextpageid']['left'] = '<a href="./BookUpdateList.aspx?ChannelId=-1&StartTime=';
$jieqiCollect['listcollect']['0']['nextpageid']['right'] = '">下一页</a>';
$jieqiCollect['listcollect']['0']['nextpageid']['middle'] = '!!!!';
$jieqiCollect['listcollect']['0']['maxpagenum'] = '5';
$jieqiCollect['listcollect']['2']['title'] = '周排行榜';
$jieqiCollect['listcollect']['2']['urlpage'] = 'http://www.qidian.com/Book/BookPotentialList.aspx?Type=Book';
$jieqiCollect['listcollect']['2']['articleid']['left'] = '= new Book(\'';
$jieqiCollect['listcollect']['2']['articleid']['right'] = '\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',~);';
$jieqiCollect['listcollect']['2']['articleid']['middle'] = '$$$$';
$jieqiCollect['listcollect']['2']['startpageid'] = '';
$jieqiCollect['listcollect']['2']['nextpageid'] = '';
$jieqiCollect['listcollect']['2']['maxpagenum'] = '0';
$jieqiCollect['listcollect']['3']['title'] = '总推荐榜';
$jieqiCollect['listcollect']['3']['urlpage'] = 'http://www.qidian.com/Book/BookStore.aspx?Type=Cmd&F=W';
$jieqiCollect['listcollect']['3']['articleid']['left'] = '= new Book(\'';
$jieqiCollect['listcollect']['3']['articleid']['right'] = '\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',\'~\',~);';
$jieqiCollect['listcollect']['3']['articleid']['middle'] = '$$$$';
$jieqiCollect['listcollect']['3']['startpageid'] = '';
$jieqiCollect['listcollect']['3']['nextpageid'] = '';
$jieqiCollect['listcollect']['3']['maxpagenum'] = '0';

?>